//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StereoScopica.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::StereoScopica.UISettings UISettings
        {
            get
            {
                return ((global::StereoScopica.UISettings)(this["UISettings"]));
            }
            set
            {
                this["UISettings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::StereoScopica.CameraSettings Camera0 {
            get {
                return ((global::StereoScopica.CameraSettings)(this["Camera0"]));
            }
            set {
                this["Camera0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::StereoScopica.CameraSettings Camera1 {
            get {
                return ((global::StereoScopica.CameraSettings)(this["Camera1"]));
            }
            set {
                this["Camera1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::StereoScopica.TexturedPlane ImagePlaneLeft {
            get {
                return ((global::StereoScopica.TexturedPlane)(this["ImagePlaneLeft"]));
            }
            set {
                this["ImagePlaneLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::StereoScopica.TexturedPlane ImagePlaneRight {
            get {
                return ((global::StereoScopica.TexturedPlane)(this["ImagePlaneRight"]));
            }
            set {
                this["ImagePlaneRight"] = value;
            }
        }
        
    }
}
